{
 "title": "Service Observations",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(nats_latency_total_duration_sum, service)"
   },
   { "name": "range", "label": "Range", "query": "1m,5m,10m" }
  ]
 },
 "panels": [
  {
   "title": "Service Duration Percentiles",
   "type": "graph",
   "description": "Percentile of service time spent in the service ",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s", "label": "duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.10, sum(rate(nats_latency_service_duration_bucket{service=~\"${service}\"}[$range])) by (le,service))",
     "legendFormat": "{{service}} 10th %"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(nats_latency_service_duration_bucket{service=~\"${service}\"}[$range])) by (le,service))",
     "legendFormat": "{{service}} 50th %"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nats_latency_service_duration_bucket{service=~\"${service}\"}[$range])) by (le,service))",
     "legendFormat": "{{service}} 95th %"
    }
   ]
  },
  {
   "title": "Total Duration Percentiles",
   "type": "graph",
   "description": "Percentile of total time spent in the service and in the total which includes network overhead ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "s", "label": "duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.10, sum(rate(nats_latency_total_duration_bucket{service=~\"${service}\"}[$range])) by (le,service))",
     "legendFormat": "{{service}} 10th %"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(nats_latency_total_duration_bucket{service=~\"${service}\"}[$range])) by (le,service))",
     "legendFormat": "{{service}} 50th %"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nats_latency_total_duration_bucket{service=~\"${service}\"}[$range])) by (le,service))",
     "legendFormat": "{{service}} 95th %"
    }
   ]
  },
  {
   "title": "Average Service Duration",
   "type": "graph",
   "description": "Average times taken to serve a request.\n\n* **service time** is the time taken to execute the service\n* **total time** includes network latencies between all parties",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "s", "label": "duration" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nats_latency_service_duration_sum{service=~\"${service}\"}[$range]) / rate(nats_latency_service_duration_count{service=~\"${service}\"}[$range])) by (service)",
     "legendFormat": "{{service}} service time"
    },
    {
     "expr": "sum(rate(nats_latency_total_duration_sum{service=~\"${service}\"}[$range]) / rate(nats_latency_total_duration_count{service=~\"${service}\"}[$range])) by (service)",
     "legendFormat": "{{service}} total time"
    }
   ]
  },
  {
   "title": "System RTT Times Percentiles",
   "type": "graph",
   "description": "Time distribution spent traversing the NATS cluster",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s", "label": "rtt time" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.10, sum(rate(nats_latency_system_rtt_bucket{service=~\"${service}\"}[$range])) by (service, le))",
     "legendFormat": "{{service}} 10th %"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(nats_latency_system_rtt_bucket{service=~\"${service}\"}[$range])) by (service, le))",
     "legendFormat": "{{service}} 50th %"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nats_latency_system_rtt_bucket{service=~\"${service}\"}[$range])) by (service, le))",
     "legendFormat": "{{service}} 95th %"
    }
   ]
  },
  {
   "title": "Requestor RTT Times Percentiles",
   "type": "graph",
   "description": "Response time distribution between NATS and the Requesting Client",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "s", "label": "rtt time" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.10, sum(rate(nats_latency_requestor_rtt_bucket{service=~\"${service}\"}[$range])) by (service, le))",
     "legendFormat": "{{service}} 10th %"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(nats_latency_requestor_rtt_bucket{service=~\"${service}\"}[$range])) by (service, le))",
     "legendFormat": "{{service}} 50th %"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nats_latency_requestor_rtt_bucket{service=~\"${service}\"}[$range])) by (service, le))",
     "legendFormat": "{{service}} 95th %"
    }
   ]
  },
  {
   "title": "Responder RTT Times Percentiles",
   "type": "graph",
   "description": "Response time distribution between NATS and the Service",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "s", "label": "rtt time" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.10, sum(rate(nats_latency_responder_rtt_bucket{service=~\"${service}\"}[$range])) by (service, le))",
     "legendFormat": "{{service}} 10th %"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(nats_latency_responder_rtt_bucket{service=~\"${service}\"}[$range])) by (service, le))",
     "legendFormat": "{{service}} 50th %"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nats_latency_responder_rtt_bucket{service=~\"${service}\"}[$range])) by (service, le))",
     "legendFormat": "{{service}} 95th %"
    }
   ]
  },
  {
   "title": "Observations Statuses Received",
   "type": "graph",
   "description": "Number of observations received by status",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "observations / second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nats_latency_observation_status_count{service=~\"${service}\"}[$range])) by (service,status)",
     "legendFormat": "{{service}} {{status}}"
    }
   ]
  }
 ]
}